### ISSUE TITLE
Pinterest support

### ISSUE THREAD

**Issue by Lameur** [ammargitham/WallFlow#33]
Is there a support for Pinterest planned for the future ?

**Comment by ammargitham** [comment]
I checked the Pinterest API documentation. It's unclear if the app usage is covered under their API usage terms. I go through it once more before I make a final decision.

Also, it requires an API access key and I don't want to release the app tied to any API access key for any source. So each user will have to sign up for an access key to use it in the app. So that is also something to consider.

**Comment by Lameur** [comment]
Ok, thanks you for your amazing app!

**Comment by ammargitham** [comment]
I'll close this for now due to the reasons I specified previously. I can revisit this if there is more interest in Pinterest support.
